CREATE DATABASE web_day7;

USE web_day7;


CREATE TABLE STUDENT(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	IDENTITY_NUMBER VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL, 
    DOB DATE,
    GENDER VARCHAR(6),
    PRIMARY KEY ( ID )
);

SELECT * FROM STUDENT;
